# Variable

In [35]:
x <- 5
cat(x, "\n")
cat(typeof(x))

5 
double

In [36]:
x <- "string string"
cat(x, "\n")
cat(typeof(x))

string string 
character

In [37]:
text <- "Bangladesh"
paste("I love", text)

[1] "I love Bangladesh"

In [39]:
var1 = 5
var2 = 10
cat(var1+var2)

15

In [42]:
# numeric value 
x <- 10.5
cat(x, "\n")
cat(class(x))

10.5 
numeric

In [45]:
# integer value
x <- 15L
cat(x, "\n")
cat(typeof(x), "\n")
cat(class(x))

15 
integer 
integer

In [46]:
# complex value
x <- 3+2i
cat(x, "\n")
cat(typeof(x), '\n')
cat(class(x))

3+2i 
complex 
complex

In [49]:
# type conversion
x = 10 # numeric type
y = 5L # integer type 

xx = as.integer(x) # from numeric to integer 
cat(xx, "\n")
cat(typeof(xx))

10 
integer

In [51]:
# type conversion
x = 10 # numeric type
y = 5L # integer type

yy = as.numeric(y) # integer to numeric 
cat(yy, "\n")
cat(typeof(yy), "\n")
cat(class(yy), "\n")

5 
double 
numeric 


# Some Mathematical Operation 

In [52]:
x = 16 
cat(sqrt(x)) 

4

In [56]:
x = 4
y = 2
div = x/y
cat(div, "\n")
cat(x*y, "\n")
cat(x+y, "\n")
cat(x-y, "\n")

2 
8 
6 
2 


In [59]:
x = c(2,5,4,3,7,5,7,9)
cat(min(x), "\n")
cat(max(x), "\n")

2 
9 


In [60]:
x = -4.56
cat(abs(x))

4.56

In [62]:
x = 4.6
cat(ceiling(x), "\n")
cat(floor(x), "\n")

5 
4 


In [67]:
x = 3
y = 2
z = x%/%y #integer value 
cat(z)

1

# String 

In [1]:
str <- "Hello world"
print(str)

[1] "Hello world"


In [4]:
a <- "I"
b <- "love"
c <- "Bangladeshi food"

print(paste(a, b, c))
print(paste(a, b, c, sep="-"))
print(paste(a, b, c, sep="", collapse=""))


[1] "I love Bangladeshi food"
[1] "I-love-Bangladeshi food"
[1] "IloveBangladeshi food"


In [10]:
str = format(123.456786, digits=5)
print(str)

str2 = format(6)
print(str2)

str3 = format(15.8, width=6)
print(str3)

str4 = format("Hello", width=8, justify="l")
print(str4)

[1] "123.46"
[1] "6"
[1] "  15.8"
[1] "Hello   "


In [12]:
ch_num = nchar("Bangladesh is a beautiful country")
print(ch_num)


[1] 33
[1] "33"


In [15]:
print(toupper("How are you?"))
print(tolower("I am fine!"))

[1] "HOW ARE YOU?"
[1] "i am fine!"


In [16]:
print(substring("Bangladesh", 3, 7))

[1] "nglad"


In [38]:
text1 = "Bangladesh is"
text2 = "Beautiful"

paste(text1, text2)

[1] "Bangladesh is Beautiful"

In [64]:
# Checking if a small string is available in a big string 
str <- "Hello World"
cat(grepl("H", str), "\n")
cat(grepl("ll", str), "\n")

TRUE 
TRUE 


In [66]:
str <- "We are the so-called \"Vikings\", from the north."
print(str)
cat(str, "\n")

[1] "We are the so-called \"Vikings\", from the north."
We are the so-called "Vikings", from the north. 


# For Loop

In [3]:
x <- c(1,2,3,4,5,6,7,8,9)

for (i in x){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9


In [4]:
for (i in 1:5){
    print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [8]:
x <- c(1,2,3,4,5,6,7,8,9)
for (i in x){
    if (i%%2 == 0){
        print(i)
    } 
}

[1] 2
[1] 4
[1] 6
[1] 8


In [25]:
fun_fac <- function(x){
    for (i in 1:x){
        for (j in 1:5){
            cat(j,'\n')
        }
        cat("\n")
    }
}

fun_fac(3)

1 
2 
3 
4 
5 

1 
2 
3 
4 
5 

1 
2 
3 
4 
5 



# While Loop

In [28]:
i = 1

while (i<6){
    print(i)
    i = i + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [30]:
i=0

while (i<11){
    if (i%%2 == 0){
        cat(i, "\n")
    }
    i = i+1
}

0 
2 
4 
6 
8 
10 


# Function

In [17]:
print(seq(5, 23))

 [1]  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23


In [20]:
avg = mean(1:10)
print(avg)

[1] 5.5


In [21]:
addition = sum(1:10)
print(addition)

[1] 55


In [23]:
func <- function(a){
    for (i in 1:a){
        b <- i^2
        print(b)
    }
}

func(5)

[1] 1
[1] 4
[1] 9
[1] 16
[1] 25


In [24]:
func <- function(a, b, c){
    add <- a + b + c
    add_sub <- a + b - c
    print(add)
    print(add_sub)
}

func(2,3,4)

[1] 9
[1] 1


In [25]:
func <- function(a, b, c){
    add <- a + b + c
    add_sub <- a + b - c
    print(add)
    print(add_sub)
}

func(b=2, a=3, c=4)

[1] 9
[1] 1


In [30]:
func <- function(a=2, b=4, c=6){
    add <- a+b+c
    add_sub <- a+b-c
    print(add)
    print(add_sub)
}

print(func())
#print(func(7,7,7))

[1] 12
[1] 0
[1] 0


In [15]:
func <- function(a, b, c){
    if (a>b && a>c){
        print(" a is greater than a and b")
    }
    else if (b>a && b>c){
        print("b is greater than a and c")
    }
    else if (c>a && c>b){
        print("b is greater than a and c")
    }
    else{
        print("No condition match")
    }
}

func(2,4,6)
func(4,6,2)
func(6,4,2)

[1] "b is greater than a and c"
[1] "b is greater than a and c"
[1] " a is greater than a and b"


# Vector

In [68]:
fruits <- c("apple", "orange", "banana")
cat(fruits)

apple orange banana

In [75]:
cat(fruits[2])

orange

In [72]:
# vector length 
cat(length(fruits)) 

3

In [73]:
# vector sort
cat(sort(fruits)) 

apple banana orange

In [74]:
numbers <- c(5,4,3,4,5,6,7,6,5,8,9,5)
cat(sort(numbers))

3 4 4 5 5 5 5 6 6 7 8 9

In [69]:
numbers <- c(1,2,3)
numbers

[1] 1 2 3

In [70]:
numbers <- 1:10
numbers

[1]  1  2  3  4  5  6  7  8  9 10

In [71]:
number <- 1.5:7.5
cat(number)

1.5 2.5 3.5 4.5 5.5 6.5 7.5

In [81]:
fruits <- c("banana", "apple", "orange", "mango", "lemon")
cat(fruits[c(2, 5)], "\n")
cat(fruits[2:5], "\n")
cat(fruits[-1], "\n")
cat(fruits[c(-1)], "\n")

apple lemon 
apple orange mango lemon 
apple orange mango lemon 
apple orange mango lemon 


In [82]:
fruits[2] <- "watermelon" 
cat(fruits) 

banana watermelon orange mango lemon

In [83]:
repeat_each <- rep(c(1,2,3), each=3)
cat(repeat_each)

1 1 1 2 2 2 3 3 3

In [84]:
repeat_time <- rep(c(1,2,3), times=3)
cat(repeat_time)

1 2 3 1 2 3 1 2 3

In [87]:
# repeat individual 
repeat_indepent <- rep(c(1,2,3), times = c(5,2,1))
cat(repeat_indepent)

1 1 1 1 1 2 2 3

In [88]:
numbers <- seq(from=0, to=100, by=20)
cat(numbers)

0 20 40 60 80 100

# List

In [93]:
ele_list <- list("apple", "banana", "cherry")
ele_list

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

In [94]:
ele_list[2]

[[1]]
[1] "banana"

In [95]:
ele_list[2] <- "blackberry"
ele_list

[[1]]
[1] "apple"

[[2]]
[1] "blackberry"

[[3]]
[1] "cherry"

In [96]:
# finding length
length(ele_list)

[1] 3

In [97]:
# checking is a value in list
"blackberry" %in% ele_list

[1] TRUE

In [100]:
# appending new element
ele_list <- list("apple", "banana", "cherry")
append(ele_list, "grape", after=2)
ele_list

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "grape"

[[4]]
[1] "cherry"

[[1]]
[1] "apple"

[[2]]
[1] "banana"

[[3]]
[1] "cherry"

In [101]:
ele_list <- list("apple", "banana", "cherry")
new_list <- ele_list[-1]
new_list

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

In [104]:
l = list("bana", "mango", "apple", "cherry", "grape")
l[2:5]

[[1]]
[1] "mango"

[[2]]
[1] "apple"

[[3]]
[1] "cherry"

[[4]]
[1] "grape"

In [105]:
thislist <- list("apple", "banana", "cherry")

for (i in thislist){
    print(i)
}

[1] "apple"
[1] "banana"
[1] "cherry"


In [106]:
# join two list
list1 <- list("a", "b", "c")
list2 <- list(1, 2, 3)

com_list <- c(list1, list2)
com_list

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3

# Matrices

In [107]:
mat <- matrix(c(1,2,3,4,5,6), nrow=3, ncol=2)
mat

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [108]:
mat <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
mat

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

In [109]:
mat[1,2]

[1] "cherry"

In [111]:
mat[,2]

[1] "cherry" "orange"

In [112]:
mat <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
mat

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

In [113]:
mat[c(1, 2),] 

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

In [114]:
mat[, c(1,2)] 

[,1]   [,2]     
[1,] apple  orange   
[2,] banana grape    
[3,] cherry pineapple

In [115]:
mat <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
mat

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig

In [116]:
new_mat <- cbind(mat, c("A", "B", "C"))
new_mat

[,1]   [,2]      [,3]  [,4]
[1,] apple  orange    pear  A   
[2,] banana grape     melon B   
[3,] cherry pineapple fig   C

In [118]:
new_mat <- rbind(mat, c("M", "N", "O"))
new_mat

[,1]   [,2]      [,3] 
[1,] apple  orange    pear 
[2,] banana grape     melon
[3,] cherry pineapple fig  
[4,] M      N         O

In [119]:
# remove 1st row and 1st column
mat <- matrix(c("apple", "banana", "cherry", "orange", "mango", "pineapple"), nrow = 3, ncol =2)
mat

[,1]   [,2]     
[1,] apple  orange   
[2,] banana mango    
[3,] cherry pineapple

In [120]:
new_mat <- mat[-c(1), -c(1)]
new_mat

[1] "mango"     "pineapple"

In [122]:
"banana" %in% mat

[1] TRUE

In [123]:
dim(mat)

[1] 3 2

In [124]:
length(mat)

[1] 6

In [125]:
mat <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
mat

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

In [126]:
for (row in 1:nrow(mat)){
    for (col in 1:nrow(mat)){
        print(mat[row, col])
    }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"


In [127]:
# combine two matrix
mat1 <- matrix(c("A", "B", "C", "D", "E", "F"), nrow=2, ncol=3)
mat2 <- matrix(c("1", "2", "3", "4", "5", "6"), nrow=2, ncol=3)
new_mat <- rbind(mat1, mat2)
new_mat

[,1] [,2] [,3]
[1,] A    C    E   
[2,] B    D    F   
[3,] 1    3    5   
[4,] 2    4    6

In [128]:
new_mat <- cbind(mat1, mat2)
new_mat

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] A    C    E    1    3    5   
[2,] B    D    F    2    4    6

# Arrays

In [130]:
arr <- c(1:24)
arr

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

In [131]:
new_arr <- array(arr, dim=c(4, 3, 2))
new_arr


, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

In [135]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim = c(4, 3, 2))

2 %in% multiarray 

[1] TRUE

In [136]:
thisarray

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

In [138]:
dim(multiarray)

[1] 4 3 2

In [140]:
length(multiarray)

[1] 24

In [142]:
thisarray <- c(1:24)
multiarray <- array(thisarray, dim=c(4,3,2))

for (x in multiarray){
    print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24


# Data Frame

In [164]:
data_frame <- data.frame(
    Training = c("A", "B", "C"),
    Pulse = c(10, 20, 30),
    Duration = c(15, 30, 45)
)
data_frame

Training Pulse Duration
1 A        10    15      
2 B        20    30      
3 C        30    45

In [165]:
# summary of the data frame
summary(data_frame)

 Training     Pulse       Duration   
 A:1      Min.   :10   Min.   :15.0  
 B:1      1st Qu.:15   1st Qu.:22.5  
 C:1      Median :20   Median :30.0  
          Mean   :20   Mean   :30.0  
          3rd Qu.:25   3rd Qu.:37.5  
          Max.   :30   Max.   :45.0  

In [166]:
# access item
data_frame[1]

Training
1 A       
2 B       
3 C

In [167]:
data_frame[["Training"]]

[1] A B C
Levels: A B C

In [168]:
data_frame$Training

[1] A B C
Levels: A B C

In [169]:
# adding rows in data frame
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

New_row_DF <- rbind(Data_Frame, c("Strength", 110, 110))
New_row_DF

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Strength 110   110

In [170]:
# adding new column 
New_row_DF <- cbind(Data_Frame, c(5, 6, 110))
New_row_DF

Training Pulse Duration c(5, 6, 110)
1 Strength 100   60         5         
2 Stamina  150   30         6         
3 Other    120   45       110

In [171]:
new_remove <- New_row_DF[-c(1), -c(1)]
new_remove

Pulse Duration c(5, 6, 110)
2 150   30         6         
3 120   45       110

In [172]:
print(dim(new_remove))
print(nrow(new_remove))
print(ncol(new_remove))
print(length(new_remove))

[1] 2 3
[1] 2
[1] 3
[1] 3


In [173]:
# combining two data frame
Data_Frame1 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame2 <- data.frame (
  Training = c("Stamina", "Stamina", "Strength"),
  Pulse = c(140, 150, 160),
  Duration = c(30, 30, 20)
)

New_Data_Frame <- rbind(Data_Frame1, Data_Frame2)
New_Data_Frame 

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Stamina  140   30      
5 Stamina  150   30      
6 Strength 160   20

In [174]:
Data_Frame3 <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

Data_Frame4 <- data.frame (
  Steps = c(3000, 6000, 2000),
  Calories = c(300, 400, 300)
)

New_Data_Frame1 <- cbind(Data_Frame3, Data_Frame4)
New_Data_Frame1 

Training Pulse Duration Steps Calories
1 Strength 100   60       3000  300     
2 Stamina  150   30       6000  400     
3 Other    120   45       2000  300

# Factors

In [180]:
fac <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))
fac

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

In [181]:
fac[2]

[1] Rock
Levels: Classic Jazz Pop Rock

In [176]:
levels(fac) 

[1] "Classic" "Jazz"    "Pop"     "Rock"

In [177]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Other"))

levels(music_genre) 

[1] "Classic" "Jazz"    "Pop"     "Rock"    "Other"

In [178]:
length(music_genre)

[1] 8

In [182]:
fac <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))
fac

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

In [183]:
fac[3] <- "Pop"
fac

[1] Jazz    Rock    Pop     Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

In [184]:
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), 
                      levels = c("Classic", "Jazz", "Pop", "Rock", "Opera"))

music_genre[3] <- "Opera"

music_genre[3]

[1] Opera
Levels: Classic Jazz Pop Rock Opera